version: 2.1

orbs:
  change-api: financial-times/change-api@0.24.0
  aws-cli: circleci/aws-cli@0.1.17

jobs:
  lint_terraform:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: sudo ~/project/.circleci/install_terraform.sh
      - aws-cli/install
      - aws-cli/setup:
          configure-default-region: false
      - run: terraform fmt -check=true fastly/terraform/

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  unit_test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: npm run test:unit

  integration_test_int:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: COMPONENT_TABLE="origami-build-service-int-components" MODULE_BUCKET_NAME="origami-build-service-int-modules" npm run bootstrap
      - run: HOST="https://origami-build-service-v3-dev.in.ft.com" npm run test:integration

  deploy_int:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: sudo ~/project/.circleci/install_terraform.sh
      - aws-cli/install
      - aws-cli/setup:
          configure-default-region: false
      - run: npx serverless package --stage int --package .serverless-package
      - run: npx serverless deploy additionalstacks --conceal --stage int --region eu-west-1
      - run: npx serverless deploy additionalstacks --conceal --stage int --region us-west-1 --stack permanent-dynamo
      - run: npx serverless deploy --skip-additionalstacks --conceal --stage int --region eu-west-1 --package .serverless-package
      - run: npx serverless deploy --skip-additionalstacks --conceal --stage int --region us-west-1 --package .serverless-package
      - run: rm -f terraform.tfstate fastly/terraform/qa_override.tf fastly/terraform/production_override.tf
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_DEV terraform init fastly/terraform/
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_DEV terraform import -config=fastly/terraform fastly_service_v1.app $FASTLY_SERVICE_ID_DEV
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_DEV terraform apply --auto-approve fastly/terraform

  deploy_staging:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: sudo ~/project/.circleci/install_terraform.sh
      - aws-cli/install
      - aws-cli/setup:
          configure-default-region: false
      - run: npx serverless package --stage qa --package .serverless-package
      - run: npx serverless deploy additionalstacks --conceal --stage qa --region eu-west-1
      - run: npx serverless deploy additionalstacks --conceal --stage qa --region us-west-1 --stack permanent-dynamo
      - run: npx serverless deploy --skip-additionalstacks --conceal --stage qa --region eu-west-1 --package .serverless-package
      - run: npx serverless deploy --skip-additionalstacks --conceal --stage qa --region us-west-1 --package .serverless-package
      - run: rm -f terraform.tfstate fastly/terraform/int_override.tf fastly/terraform/production_override.tf
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_QA terraform init fastly/terraform/
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_QA terraform import -config=fastly/terraform fastly_service_v1.app $FASTLY_SERVICE_ID_QA
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_QA terraform apply --auto-approve fastly/terraform

  deploy_production:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: sudo ~/project/.circleci/install_terraform.sh
      - aws-cli/install
      - aws-cli/setup:
          configure-default-region: false
      - run: npx serverless package --stage prod --package .serverless-package
      - run: npx serverless deploy additionalstacks --conceal --stage prod --region eu-west-1
      - run: npx serverless deploy additionalstacks --conceal --stage prod --region us-west-1 --stack permanent-dynamo
      - run: npx serverless deploy --skip-additionalstacks --conceal --stage prod --region eu-west-1 --package .serverless-package
      - run: npx serverless deploy --skip-additionalstacks --conceal --stage prod --region us-west-1 --package .serverless-package
      - run: rm -f terraform.tfstate fastly/terraform/int_override.tf fastly/terraform/production_override.tf
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_PROD terraform init fastly/terraform/
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_PROD terraform import -config=fastly/terraform fastly_service_v1.app $FASTLY_SERVICE_ID_PROD
      - run: FASTLY_API_KEY=$FASTLY_API_KEY_PROD terraform apply --auto-approve fastly/terraform

workflows:
  deploy:
    jobs:
      - lint_terraform
      - lint
      - unit_test
      - deploy_int:
          requires:
            - lint
            - unit_test
            - lint_terraform
          filters:
            branches:
              ignore:
                - master
      - change-api/release-log:
          requires:
            - deploy_int
          systemCode: 'origami-build-service-v3'
          environment: 'dev'
          slackChannels: 'origami-deploys'
      - integration_test_int:
          requires:
            - deploy_int
      - deploy_staging:
          requires:
            - lint
            - unit_test
            - lint_terraform
          filters:
            branches:
              only:
                - master
      - change-api/release-log:
          requires:
            - deploy_staging
          systemCode: 'origami-build-service-v3'
          environment: 'test'
          slackChannels: 'origami-deploys'